### ISSUE TITLE
Some insights in prebuild-install downloads

### ISSUE THREAD

**Issue by mathiask88** [prebuild/welcome#3]
I was interested in the prebuild download counts for my native module and I thought it may be interesting to see these for the top 10 `prebuild-install` dependents.

![image](https://user-images.githubusercontent.com/4368785/30241501-fa4eddc6-9584-11e7-9c54-d32d7c740e6a.png)

![image](https://user-images.githubusercontent.com/4368785/30241509-118f00d8-9585-11e7-9d03-f5a9b4cc1711.png)

![image](https://user-images.githubusercontent.com/4368785/30241516-1f5bc106-9585-11e7-8c60-a1b26a1c38d5.png)

![image](https://user-images.githubusercontent.com/4368785/30241547-ca3d0198-9585-11e7-90f2-5a8de3cde88a.png)

![image](https://user-images.githubusercontent.com/4368785/30241550-d964be40-9585-11e7-8d8c-c088bdb77679.png)

![image](https://user-images.githubusercontent.com/4368785/30241554-e6e38b82-9585-11e7-9206-68f61b1879d4.png)

![image](https://user-images.githubusercontent.com/4368785/30241559-f5acd01a-9585-11e7-9216-1be42008d05e.png)

![image](https://user-images.githubusercontent.com/4368785/30241566-25582fda-9586-11e7-91c5-acd3a3d37337.png)

![image](https://user-images.githubusercontent.com/4368785/30241573-36d808e8-9586-11e7-9bf3-863e8253f4b8.png)

![image](https://user-images.githubusercontent.com/4368785/30241579-58902eb6-9586-11e7-9559-2272a7f10ede.png)

**Comment by ralphtheninja** [comment]
@mathiask88 Any tool you feel like sharing?

**Comment by mathiask88** [comment]
Sure, I can make a CLI tool out of my code.

I still think about the numbers..  `bufferutil` has ~80k downloads/week and the latest release is 2 month old, but the accumulated github release download count is only 60k. Either there are missing prebuilts or npm and github count different. Am I missing something? Edit: Or does the caching mechanism have such a big impact?

**Comment by ralphtheninja** [comment]
So github download count is 60k in _total_? It seems like it. Should be possible to test otherwise.

**Comment by mathiask88** [comment]
@ralphtheninja Sorry for the delay, but I finally created a repo for [prebuild-stats](https://github.com/mathiask88/prebuild-stats ) Don't expect too much functionality :D

**Comment by mathiask88** [comment]
@ralphtheninja May I transfer the `prebuild-stats` repo to this org? I think it fits best here.

**Comment by ralphtheninja** [comment]
@mathiask88 Do it! 😄
